version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 100
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 100